# Generated by Django 3.0 on 2019-12-24 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191224_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 9, 41, 12, 369771), verbose_name='date published'),
        ),
    ]
