# Generated by Django 3.0 on 2019-12-24 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191224_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 10, 0, 38, 375883), verbose_name='date published'),
        ),
    ]
