# Generated by Django 3.0 on 2019-12-24 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191224_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 10, 3, 17, 942227), verbose_name='date published'),
        ),
    ]
